<?php

/**
 * @file
 * Primary module hooks for cdp_pages module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function cdp_pages_theme($existing, $type, $theme, $path) {
  return [
    'cdp_page' => [
      'variables' => [
        'string' => NULL,
      ],
    ],
    'cdp_page_with_preprocess' => [
      'variables' => [
        'string' => NULL,
      ],
    ],
    'cdp_page_with_suggestion' => [
      'variables' => [
        'string' => NULL,
      ],
    ],
    'cdp_page_with_theme_template' => [
      'variables' => [
        'string' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function cdp_pages_preprocess_cdp_page_with_preprocess(&$variables) {
  $string_that_overrides_string = 'It works, but is preprocessed at: ' . date('Y-m-d H:i:s');
  $variables['string'] = $string_that_overrides_string;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function cdp_pages_theme_suggestions_cdp_page_with_suggestion(array $variables) {
  $template_machine_name_from_hook_theme = $variables['theme_hook_original'];
  $currently_logged_in_user = \Drupal::currentUser();
  $currently_logged_in_user_id = $currently_logged_in_user->id();

  return [
    $template_machine_name_from_hook_theme . '__' . $currently_logged_in_user_id,
  ];
}
