<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function cdp_custom_signin_form_user_register_form_alter(&$form,FormStateInterface $form_state,$form_id) {

  $form['account']['name']['#access'] = FALSE;
  $form['account']['name']['#required'] = FALSE;

  $form['register_roles'] = [
    '#type' => 'select',
    '#title' => t('Roles'),
    '#options' => [
      'developer' => t('Developer'),
      'tech_lead' => t('Tech lead'),
    ],
  ];
//dump($form);
  $form['#validate'] = array_merge(['_validate_form'], $form['#validate']);
}

function _validate_form(array &$form, FormStateInterface $form_state): void {
  $mail = $form_state->getValue('mail');
  $user = user_load_by_mail($mail);
  $role = $form_state->getCompleteForm()['register_roles']['#value'];

  if (!$user && $role === 'developer' || $role === 'tech_lead') {
    $form_state->setValue('name', $mail);
    $form_state->setValue('roles', $role);
  }
}
