<?php
/**
 * @file
 * Primary module hooks for cdp_pages module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\cdp_frontpage\Plugin\Block\ModalFormBlock;

/**
 * Implements hook_theme().
 */
function cdp_frontpage_theme($existing, $type, $theme, $path) {


  return [
    'cdp_modal_form'=> [
      'variables' => [
        'forma1' => 'l',
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess().
 */
function cdp_frontpage_preprocess(&$variables, $hook) {
//  dump($hook);
}