<?php

/**
 * @file
 * Provides a cdp_task_entity entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function cdp_task_entity_theme() {
  return [
    'cdp_task_entity' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for cdp_task_entity templates.
 *
 * Default template: cdp-task-entity.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the cdp_task_entity information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_cdp_task_entity(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
